name: Build and Push Docker Image for ARM64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up APPS_JSON
      run: |
        APPS_JSON='[
          {
            "url": "https://gitlab.com/dokos/payments",
            "branch": "v4"
          },
          {
            "url": "https://gitlab.com/dokos/hrms",
            "branch": "v4"
          },
          {
            "url": "https://gitlab.com/dokos/dokos",
            "branch": "v4"
          },
          {
            "url": "https://gitlab.com/dokos/hiboutik",
            "branch": "v4"
          },
          {
            "url": "https://gitlab.com/dokos/nextcloud",
            "branch": "v4"
          }
        ]'
        echo "APPS_JSON_BASE64=$(echo $APPS_JSON | base64 -w 0)" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: images/custom/Containerfile
        platforms: linux/arm64
        push: true
        tags: ghcr.io/${{ github.repository }}:latest-arm64
        build-args: |
          FRAPPE_PATH=https://gitlab.com/dokos/dodock
          FRAPPE_BRANCH=v4
          PYTHON_VERSION=3.11
          NODE_VERSION=18.18.2
          APPS_JSON_BASE64=${{ env.APPS_JSON_BASE64 }}
        no-cache: true
